package com.example.technicaltask.constants

import com.example.technicaltask.model.Country

val countries = listOf(
    Country("Azerbaijan"),
    Country("United States"),
    Country("United Kingdom"),
    Country("Canada"),
    Country("Germany"),
    Country("France"),
    Country("Italy"),
    Country("Spain"),
    Country("Japan"),
    Country("China"),
    Country("India"),
    Country("Brazil"),
    Country("Australia"),
    Country("Russia"),
    Country("Mexico"),
    Country("South Korea"),
    Country("Turkey"),
    Country("Netherlands"),
    Country("Switzerland"),
    Country("Sweden"),
    Country("Norway"),
    Country("Denmark"),
    Country("Finland"),
    Country("Poland"),
    Country("Ukraine"),
    Country("Argentina"),
    Country("South Africa"),
    Country("Saudi Arabia"),
    Country("United Arab Emirates"),
    Country("Indonesia"),
    Country("Thailand"),
    Country("Vietnam"),
    Country("Malaysia"),
    Country("Singapore"),
    Country("Portugal"),
    Country("Greece"),
    Country("Egypt"),
    Country("Colombia"),
    Country("Chile"),
    Country("New Zealand")
)